[env:release]
platform               = espressif32
board                  = esp32dev
framework              = arduino
board_build.flash_mode = dio
board_build.partitions = min_spiffs.csv
board_build.filesystem = littlefs
monitor_speed          = 115200
upload_speed           = 921600

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_NIMBLE_ENABLED=1

lib_deps =
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    olikraus/U8g2
    xreef/PCF8574 library
    h2zero/NimBLE-Arduino
    marvinroger/async-mqtt-client
    me-no-dev/ESP Async WebServer
    me-no-dev/AsyncTCP
    bblanchon/ArduinoJson
    ayushsharma82/ElegantOTA
    lorol/LittleFS_esp32

[env:debug]
extends        = env:release
build_flags    =
    -DCORE_DEBUG_LEVEL=4
    -DCONFIG_NIMBLE_ENABLED=1
    -DDEBUG_BUILD

[env:native]
platform = native
lib_deps =
    bblanchon/ArduinoJson
